### ISSUE TITLE
RLCM doesn't start

### ISSUE THREAD

**Issue by MrForgeMan** [loriswit/rlcm#3] opened 2023-07-24 18:43 UTC
When I try to launch the "rlcm.exe" file, nothing happens. I tried launching as administrator, still nothing. What should I do?

**Comment by loriswit** [comment] 2023-07-24 21:58
It's hard to investigate without more info. What is your operating system? Which version? When is the last time you updated it? Does the event viewer say anything when you launch the program? Do you have an antivirus? Have you tried disabling it?

**Comment by MrForgeMan** [comment] 2023-07-25 17:25
I use Windows 10 Home, Version 22H2 - 1KB5028412. I don't have an antivirus. When I open Event Viewer it shows 2 errors
1 error) 
Log Name: Application
source: Application Error
Date: Tue 25.07.23 23:09:20
Event Code: 1000
Task category:(100)
Level: Error
Keywords:Classic
User: N/A
Computer: calculator
Description:
Name of the failed application: rlcm.exe , version: 1.0.0.0, timestamp: 0x601d734d
Name of the failed module: KERNELBASE.dll , version: 10.0.19041.3208, timestamp: 0xbc1cd7c0
Exception code: 0xe0434352
Error offset: 0x0013d902
ID of the failed process: 0x1fdc
Launch time of the failed application: 0x01d9bf1abebd3931
The path of the failed application: C:\Users\User\Downloads\rlcm.exe
The path of the failed module: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: b6aa7335-e14e-43bc-befe-e4f3fca6062d
Full name of the failed package:
The code of the application associated with the failed package:
Xml events:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
<Provider Name="Application Error" />
<EventID Qualifiers="0">1000</EventID>
<Version>0</Version>
<Level>2</Level>
<Task>100</Task>
<Opcode>0</Opcode>
<Keywords>0x80000000000000</Keywords>
<TimeCreated SystemTime="2023-07-25T17:09:20.2832448Z" />
<EventRecordID>53145</EventRecordID>
<Correlation />
<Execution ProcessID="0" ThreadID="0" />
<Channel>Application</Channel>
<Computer>calculator</Computer>
<Security />
</System>
<EventData>
<Data>rlcm.exe</Data>
<Data>1.0.0.0</Data>
<Data>601d734d</Data>
<Data>KERNELBASE.dll</Data>
<Data>10.0.19041.3208</Data>
<Data>bc1cd7c0</Data>
<Data>e0434352</Data>
<Data>0013d902</Data>
<Data>1fdc</Data>
<Data>01d9bf1abebd3931</Data>
<Data>C:\Users\User\Downloads\rlcm.exe</Data>
<Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
<Data>b6aa7335-e14e-43bc-befe-e4f3fca6062d</Data>
<Data>
</Data>
<Data>
</Data>
</EventData>
</Event>
2 error) 
Log Name: Application
source: .NET Runtime
Date: Tue 25.07.23 23:09:19
Event Code: 1026
Task category:Absent
Level: Error
Keywords:Classic
User: N/A
Computer: calculator
Description:
Application: rlcm.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception details: System.InvalidOperationException
in System.Linq.Enumerable.Last[[System.Char, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<Char>)
in Rlcm.Game.TrainingRoom.SetGameLocation(System.String)
in Rlcm.Game.TrainingRoom.LocateGame()
in Rlcm.Game.TrainingRoom..ctor()
in Rlcm.Windows.MainWindow..ctor()
in Rlcm.App.AppStartup(System.Object, System.Windows.StartupEventArgs)
in System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
in System.Windows.Application.<.ctor>b__1_0(System.Object)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
to System.Windows.Threading.DispatcherOperation.InvokeImpl()
in System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
in MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
in System.Windows.Threading.DispatcherOperation.Invoke()
in System.Windows.Threading.Dispatcher.ProcessQueue()
in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
in System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
in System.Windows.Application.RunDispatcher(System.Object)
in System.Windows.Application.RunInternal(System.Windows.Window)
in System.Windows.Application.Run(System.Windows.Window)
in Rlcm.App.Main()


Xml events:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
<Provider Name=".NET Runtime" />
<EventID Qualifiers="0">1026</EventID>
<Version>0</Version>
<Level>2</Level>
<Task>0</Task>
<Opcode>0</Opcode>
<Keywords>0x80000000000000</Keywords>
<TimeCreated SystemTime="2023-07-25T17:09:19.5488959Z" />
<EventRecordID>53144</EventRecordID>
<Correlation />
<Execution ProcessID="0" ThreadID="0" />
<Channel>Application</Channel>
<Computer>calculator</Computer>
<Security />
</System>
<EventData>
<Data>Application: rlcm.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception details: System.InvalidOperationException
in System.Linq.Enumerable.Last[[System.Char, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1&lt;Char&gt;)
in Rlcm.Game.TrainingRoom.SetGameLocation(System.String)
in Rlcm.Game.TrainingRoom.LocateGame()
in Rlcm.Game.TrainingRoom..ctor()
in Rlcm.Windows.MainWindow..ctor()
in Rlcm.App.AppStartup(System.Object, System.Windows.StartupEventArgs)
in System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
in System.Windows.Application.&lt;.ctor&gt;b__1_0(System.Object)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
in System.Windows.Threading.DispatcherOperation.InvokeImpl()
in System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
in MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
in System.Windows.Threading.DispatcherOperation.Invoke()
in System.Windows.Threading.Dispatcher.ProcessQueue()
in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
to System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
in System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
in System.Windows.Application.RunDispatcher(System.Object)
in System.Windows.Application.RunInternal(System.Windows.Window)
in System.Windows.Application.Run(System.Windows.Window)
in Rlcm.App.Main()

</Data>
</EventData>
</Event>

**Comment by loriswit** [comment] 2023-07-25 22:18
Thanks. It seems the program struggles to find the location of the game on your computer, and crashes as it tries to handle unexpected values. Can I ask you where your game installation comes from? (Steam, Uplay, etc.)

I won't be home until next week, so I won't be able to actually fix the issue until then. I'll probably have more questions to ask once I start working on it.

**Comment by MrForgeMan** [comment] 2023-07-26 08:38
I use Steam version of Rayman Legends.

**Comment by MrForgeMan** [comment] 2023-07-26 08:44
WAIT! Maybe I know why it isn't working! I changed some game files to play without Uplay (Exe file too). https://steamcommunity.com/sharedfiles/filedetails/?id=2842127931 I used this Steam Guide.

**Comment by MrForgeMan** [comment] 2023-07-26 20:18
Yep, because of the files is changed to play without Uplay, RLCM didn't work. Thank you anyway loriswit for helping).

**Comment by loriswit** [comment] 2023-08-01 20:44
This still looks like a bug we could fix. I'll probably take a closer look at it someday.

**Comment by loriswit** [comment] 2023-08-23 17:51
I didn't manage to reproduce the issue, but it should be fixed now. The application now ignores invalid game locations and should not crash anymore on startup. @MrForgeMan Let me know if you're still having an issue.

This was fixed in 3e14f757bfca69305d94db5984db26f17adcd3fb

**Closed by loriswit** 2023-08-23 17:51 UTC
